### PR TITLE
Delete KernelExplainerWrapper

### PR DESCRIPTION
**Pull request by SomnathSI**
*Issue #, if available:* NA

*Description of changes:* New SHAP version was released which supports text columns so we can delete the KernelExplainerWrapper now.   

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paul-cb** [comment]
I tested this notebook end-to-end using the Python3 (Data Science) kernel. I get this import error from shap regarding shap.common. 
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-f8d3941845cd> in <module>
      3 from shap import KernelExplainer
      4 from shap import sample
----> 5 from shap.common import LogitLink, IdentityLink
      6 from scipy.special import expit
      7 

ModuleNotFoundError: No module named 'shap.common'
```

**Comment by SomnathSI** [comment]
> I tested this notebook end-to-end using the Python3 (Data Science) kernel. I get this import error from shap regarding shap.common.
> 
> ```
> 
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-3-f8d3941845cd> in <module>
>       3 from shap import KernelExplainer
>       4 from shap import sample
> ----> 5 from shap.common import LogitLink, IdentityLink
>       6 from scipy.special import expit
>       7 
> 
> ModuleNotFoundError: No module named 'shap.common'
> ```

Thanks for reporting. `shap.common` got deprecated in the latest SHAP release. I removed it from the import in the notebook.

**Comment by paul-cb** [comment]
Thanks @SomnathSI for fixing this. 
I reran and got the following error:
```
---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-4-26644b487c98> in <module>
      1 automl_job_name = '<your_automl_job_name_here>'
----> 2 automl_job = AutoML.attach(automl_job_name, sagemaker_session=session)
      3 
      4 # Endpoint name
      5 ep_name = 'sagemaker-automl-' + datetime.now().strftime('%Y-%m-%d-%H-%M-%S')

/opt/conda/lib/python3.7/site-packages/sagemaker/automl/automl.py in attach(cls, auto_ml_job_name, sagemaker_session)
    121         sagemaker_session = sagemaker_session or Session()
    122 
--> 123         auto_ml_job_desc = sagemaker_session.describe_auto_ml_job(auto_ml_job_name)
    124         automl_job_tags = sagemaker_session.sagemaker_client.list_tags(
    125             ResourceArn=auto_ml_job_desc["AutoMLJobArn"]

/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in describe_auto_ml_job(self, job_name)
   1333             dict: A dictionary response with the AutoML Job description.
   1334         """
-> 1335         return self.sagemaker_client.describe_auto_ml_job(AutoMLJobName=job_name)
   1336 
   1337     def list_candidates(

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    314                     "%s() only accepts keyword arguments." % py_operation_name)
    315             # The "self" in this scope is referring to the BaseClient.
--> 316             return self._make_api_call(operation_name, kwargs)
    317 
    318         _api_call.__name__ = str(py_operation_name)

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    633             error_code = parsed_response.get("Error", {}).get("Code")
    634             error_class = self.exceptions.from_code(error_code)
--> 635             raise error_class(parsed_response, operation_name)
    636         else:
    637             return parsed_response

ClientError: An error occurred (ValidationException) when calling the DescribeAutoMLJob operation: 1 validation error detected: Value '<your_automl_job_name_here>' at 'autoMLJobName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
````

**Comment by SomnathSI** [comment]
> Thanks @SomnathSI for fixing this.
> I reran and got the following error:
> 
> ```
> ---------------------------------------------------------------------------
> ClientError                               Traceback (most recent call last)
> <ipython-input-4-26644b487c98> in <module>
>       1 automl_job_name = '<your_automl_job_name_here>'
> ----> 2 automl_job = AutoML.attach(automl_job_name, sagemaker_session=session)
>       3 
>       4 # Endpoint name
>       5 ep_name = 'sagemaker-automl-' + datetime.now().strftime('%Y-%m-%d-%H-%M-%S')
> 
> /opt/conda/lib/python3.7/site-packages/sagemaker/automl/automl.py in attach(cls, auto_ml_job_name, sagemaker_session)
>     121         sagemaker_session = sagemaker_session or Session()
>     122 
> --> 123         auto_ml_job_desc = sagemaker_session.describe_auto_ml_job(auto_ml_job_name)
>     124         automl_job_tags = sagemaker_session.sagemaker_client.list_tags(
>     125             ResourceArn=auto_ml_job_desc["AutoMLJobArn"]
> 
> /opt/conda/lib/python3.7/site-packages/sagemaker/session.py in describe_auto_ml_job(self, job_name)
>    1333             dict: A dictionary response with the AutoML Job description.
>    1334         """
> -> 1335         return self.sagemaker_client.describe_auto_ml_job(AutoMLJobName=job_name)
>    1336 
>    1337     def list_candidates(
> 
> /opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
>     314                     "%s() only accepts keyword arguments." % py_operation_name)
>     315             # The "self" in this scope is referring to the BaseClient.
> --> 316             return self._make_api_call(operation_name, kwargs)
>     317 
>     318         _api_call.__name__ = str(py_operation_name)
> 
> /opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
>     633             error_code = parsed_response.get("Error", {}).get("Code")
>     634             error_class = self.exceptions.from_code(error_code)
> --> 635             raise error_class(parsed_response, operation_name)
>     636         else:
>     637             return parsed_response
> 
> ClientError: An error occurred (ValidationException) when calling the DescribeAutoMLJob operation: 1 validation error detected: Value '<your_automl_job_name_here>' at 'autoMLJobName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*
> ```

@paul-cb Please substitute an actual AutoPilot job name here `automl_job_name = '<your_automl_job_name_here>'`. Please see the notes below the setup heading. 
<i>
In this notebook we will start with a model built by SageMaker Autopilot which was already trained on a binary classification task. Please refer to this notebook to see how to create and train an Autopilot model.
</i>

**Comment by SomnathSI** [comment]
> I am not sure if we have formal guidance, but I think we want to be able to get notebooks run without modifications on the part of the user.
> Would we be able to put in a random string to name the auto-ml job? The user can change it if they want to, but this will allow the notebook to run without changes.
> 
> @paul-cb @SomnathSI Thoughts?

@ng-j-p 
We already have commands like `bucket = '<<bucket-name>>' # customize to your bucket` in many of the notebooks. In this specific case to avoid asking the user to provide the auto-ml job we will have duplicate code from the other notebook to create an auto-ml job here.

**Comment by ng-j-p** [comment]
We need to update those bucket calls actually ...

**Comment by ng-j-p** [comment]
Can we get Yotam to leave his approval here, I will help merge it after that.

**Comment by YotamElor** [comment]
We discussed it and decided to leave that as it is. We don’t want to clone stuff that already exists in other notebooks. Also, it’s kind of an advanced example. We feel that pointing to the relevant notebook is enough.

I approve

**Comment by paul-cb** [comment]
> I am not sure if we have formal guidance, but I think we want to be able to get notebooks run without modifications on the part of the user.
> Would we be able to put in a random string to name the auto-ml job? The user can change it if they want to, but this will allow the notebook to run without changes.
> 
> @paul-cb @SomnathSI Thoughts?

I agree with @ng-j-p here. I think we should avoid having customers make modifications to run a notebook, however I do understand that for some services it's unavoidable, especially without making any changes to the implementation.

**Review by YotamElor — APPROVED** [review]
All changes look good to me. However, I did not run this version of the notebook. Somnath verified that it works.

**Review by ng-j-p — APPROVED** [review]

**Review by YotamElor — APPROVED** [review]

**Review by paul-cb — APPROVED** [review]

**Pull request merged**
