### PR TITLE
Updated DeepAR-Electricity.ipynb

### PR DESCRIPTION
**Pull request by absinr**
*Issue #, if available:* 2789 -- https://github.com/aws/amazon-sagemaker-examples/issues/2789

*Description of changes:*
Replaced deprecated method & parameters to v2.0 counterparts, as per https://sagemaker.readthedocs.io/en/stable/v2.html guidance. The original notebook with v1.x methods/parameters is still in the directory.

The method get_image_uri has been renamed in sagemaker>=2
->Changed method to: sagemaker.image_uris.retrieve

train_instance_count has been renamed in sagemaker>=2.
->Changed to: instance_count

train_instance_type has been renamed in sagemaker>=2.
->Changed to: instance_type

*Testing done:*
Ran new notebook in Studio to verify method/parameter name changes. Deprecation warnings no longer show in cell outputs.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-sagemaker-examples/blob/master/README.md)
- [x] I have tested my notebook(s) and ensured it runs end-to-end
- [x] I have linted my notebook(s) and code using `tox -e black-format,black-nb-format`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jkroll-aws** [comment]
@absinr Can you please make the V2 changes directly in the original notebook, rather than adding a new notebook? We want to move all notebooks to V2 so there is no need to preserve the V1 commands in the original one.

**Comment by absinr** [comment]
@jkroll-aws Hi Julia, added the V2 changes in the original notebook

**Comment by jkroll-aws** [comment]
@absinr Thanks, much easier to see what has changed. Please keep the dataset usage from ``s3://sagemaker-sample-files` instead of retrieving via urllib from a URL. We are also avoiding pip installs for modules such as s3fs that are included in SageMaker environments by default. What environment are you developing from that requires a pip install?

**Comment by absinr** [comment]
Hi Julia, apologies for letting this fall of my radar. I was testing out this Lab to use in a customer immersion day on SageMaker studio - not sure myself where that pip install cell came from, but will delete.

Also will update the DATA_HOST, DATA_PATH... cell to point to "sagemaker-sample-files"

**Comment by zhaoqizqwang** [comment]
Closing this PR since it was created a long time ago and didn't pass all the checks. Feel free to open a new pull request instead.

**Pull request closed without merging**
