### PR TITLE
added model training outcome viewer

### PR DESCRIPTION
**Pull request by muhyun**
*Issue #, if available:*

*Description of changes:*

It is to include a viewer on model training output files. I  also updated the training script to generate model performance outputs such as ROC-Curve, classification report, and confusion matrix. Also, added a tag to the training job.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paul-cb** [comment]
Thanks @muhyun. I'm reviewing this at the moment.

**Comment by paul-cb** [comment]
Hi @muhyun, 

I get this error when running this notebook on the second cell. 
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-159aea543f50> in <module>
      8 from sagemaker import get_execution_role, local, Model, utils, s3
      9 from sagemaker.estimator import Estimator
---> 10 from sagemaker.predictor import Predictor
     11 from sagemaker.serializers import CSVSerializer
     12 from sagemaker.deserializers import StringDeserializer

ImportError: cannot import name 'Predictor'`

**Comment by muhyun** [comment]
it should be due to the mismatched version of sagemaker python sdk. CI forces to have sdk 2, so Yohei updated the notebook to support sdk 2 to pass the CI check.

**Review by paul-cb — APPROVED** [review]
Approved.

**Pull request merged**
