### PR TITLE
added autogluon v0.0.14 support, changed the build method

### PR DESCRIPTION
**Pull request by yoheigon**
*Issue #, if available:*

*Description of changes:*
added autogluon v0.0.14 support, changed the build method

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by austinmw — APPROVED** [review]

**Review by austinmw — APPROVED** [review]
Looks good

**Comment by aaronmarkham** [comment]
You might want to nudge the PR with a commit to get CI to trigger again.

**Review by aaronmarkham — CHANGES_REQUESTED** [review]
According to the [CI result](https://rb0ce1m4ee.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=39b0f968-c618-4dc7-b80a-db200e77a56b%2Fbuild.log), it can't access a resource from ECR. Can you take a look?

**Comment by yoheigon** [comment]
We have changed the code to pass the CI check. Can you proceed the merge process?

**Review by aaronmarkham — APPROVED** [review]

**Pull request merged**
