### PR TITLE
Bring your own Container JAX - Stax

### PR DESCRIPTION
**Pull request by joglekara**
*Issue #, if available:*

*Description of changes:*
- Version pinning in Dockerfile after some testing had shown regressions
- Update Custom Estimator to include `image_uri` instead of `image_name`
- Script to train a CNN using `jax.experimental.stax` with Sagemaker Training Jobs and save the model to TF SavedModel format using `jax2tf`.
- Notebook w/ example Training Job, Deployment, and Inference

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by joglekara** [comment]
I just went through and cleaned up the formatting and grammar. 

The remaining are all `MORFOLOGIK_RULE_EN_US` from using nouns that it doesn't know, like JAX etc.

**Review by mchoi8739 — CHANGES_REQUESTED** [review]
The `trax_estimator.fit()` function returns the following error: 
```
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-8-535db342c4e9> in <module>
     10 )
     11 
---> 12 trax_estimator.fit(logs=False)

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    665         self.jobs.append(self.latest_training_job)
    666         if wait:
--> 667             self.latest_training_job.wait(logs=logs)
    668 
    669     def _compilation_job_name(self):

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1597             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1598         else:
-> 1599             self.sagemaker_session.wait_for_job(self.job_name)
   1600 
   1601     def describe(self):

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sagemaker/session.py in wait_for_job(self, job, poll)
   3069             lambda last_desc: _train_done(self.sagemaker_client, job, last_desc), None, poll
   3070         )
-> 3071         self._check_job_status(job, desc, "TrainingJobStatus")
   3072         return desc
   3073 

~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   3220                 ),
   3221                 allowed_statuses=["Completed", "Stopped"],
-> 3222                 actual_status=status,
   3223             )
   3224 

UnexpectedStatusException: Error for Training job sagemaker-jax-trax-2021-05-27-20-50-11-160: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/bin/python3 train_trax.py --train_steps 1000"
```
Would you have a look and fix?

**Comment by joglekara** [comment]
Hmm, I'm not able to reproduce. 

Any chance the error above is related to https://github.com/aws/sagemaker-python-sdk/issues/1225

Can you share which instance type you tried?

**Comment by joglekara** [comment]
Thanks for finding that!

It should be fixed now; It was related to the trax version. It is now pinned to `1.3.7`.

**Review by mchoi8739 — APPROVED** [review]

**Comment by mchoi8739** [comment]
Testing on my NI before merging

**Pull request merged**
