### PR TITLE
Updated inference pipeline example to be compatible with SageMaker SD…

### PR DESCRIPTION
**Pull request by git-mhaque**
Made changes to the example notebook for **Inference Pipeline with Scikit-learn and Linear Learner** to make it compatible with SageMaker Python SDK 2.x. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aaronmarkham — CHANGES_REQUESTED** [review]
Please add a cell to install sagemaker v2:
%pip install -U sagemaker>=2.15

In the top intro state that this requires SageMaker Python SDK v2.

Also, would you mind changing the filename? The spaces break website rendering. Standard is all lowercase with underscores for spaces. (I was going to do this in another PR, but don't want to create conflicts).

**Comment by aaronmarkham** [comment]
Fixes #1665

**Comment by git-mhaque** [comment]
Made the following changes based on feedback:
- renamed the file
- added note and code for installing SageMaker Python SDK v2

**Comment by git-mhaque** [comment]
This is ready to be merged.

**Pull request closed without merging**
