### PR TITLE
Fix links in hpo tensorflow mnist notebook

### PR DESCRIPTION
**Pull request by wiltonwu**
*Issue #, if available:* https://github.com/aws/amazon-sagemaker-examples/issues/1093

*Description of changes:*
* Updated links in `hpo_tensorflow_mnist.ipynb` notebook

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paul-cb** [comment]
Thanks @wiltonwu. The build breaks with changes in the notebook you made modifications to. Could you please fix? 
`FAILED	hyperparameter_tuning/tensorflow_mnist/hpo_tensorflow_mnist.ipynb	`

**Comment by wiltonwu** [comment]
> Thanks @wiltonwu. The build breaks with changes in the notebook you made modifications to. Could you please fix?
> `FAILED hyperparameter_tuning/tensorflow_mnist/hpo_tensorflow_mnist.ipynb `

I think the build seems to be related to a misconfigured environment with the testing framework? I see `ModuleNotFoundError` errors in the build logs. My changes are only for the links in the markdown cells, so the notebook cells and logic should remain untouched. I'll follow up with someone that's more familiar with these automated tests.

**Comment by paul-cb** [comment]
I ran your notebook with `Python 3 (Tensorflow 1.15 Python 3.7 CPU Optimized) ` it breaks at this cell: 

`estimator = TensorFlow(entry_point='mnist.py',
                  role=role,
                  framework_version='1.12.0',
                  training_steps=1000, 
                  evaluation_steps=100,
                  train_instance_count=1,
                  train_instance_type='ml.m4.xlarge',
                  base_job_name='DEMO-hpo-tensorflow')`

`train_instance_type has been renamed in sagemaker>=2.
See: https://sagemaker.readthedocs.io/en/stable/v2.html for details.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-093e35353eba> in <module>
      6                   train_instance_count=1,
      7                   train_instance_type='ml.m4.xlarge',
----> 8                   base_job_name='DEMO-hpo-tensorflow')

/usr/local/lib/python3.7/site-packages/sagemaker/tensorflow/estimator.py in __init__(self, py_version, framework_version, model_dir, image_uri, distribution, **kwargs)
    132             "train_instance_type", "instance_type", kwargs.get("instance_type"), kwargs
    133         )
--> 134         fw.validate_version_or_image_args(framework_version, py_version, image_uri)
    135         if py_version == "py2":
    136             logger.warning(

/usr/local/lib/python3.7/site-packages/sagemaker/fw_utils.py in validate_version_or_image_args(framework_version, py_version, image_uri)
    568     if (framework_version is None or py_version is None) and image_uri is None:
    569         raise ValueError(
--> 570             "framework_version or py_version was None, yet image_uri was also None. "
    571             "Either specify both framework_version and py_version, or specify image_uri."
    572         )

ValueError: framework_version or py_version was None, yet image_uri was also None. Either specify both framework_version and py_version, or specify image_uri.`

**Review by iaroslav-ai — APPROVED** [review]
LGTM

**Review by AdnanKukuljac — APPROVED** [review]

**Review by paul-cb — CHANGES_REQUESTED** [review]
A few minor changes so the notebook can run in v2. 
1. `HyperparameterTuner` is now a no-op. See here: https://sagemaker.readthedocs.io/en/stable/v2.html#delete-endpoint-for-estimators-and-hyperparametertuner
2. you need to specify `py_version` to `TensorFlow`. See here: https://sagemaker.readthedocs.io/en/stable/v2.html#changes-in-default-behavior

**Comment by wiltonwu** [comment]
> A few minor changes so the notebook can run in v2.
> 
> 1. `HyperparameterTuner` is now a no-op. See here: https://sagemaker.readthedocs.io/en/stable/v2.html#delete-endpoint-for-estimators-and-hyperparametertuner
> 2. you need to specify `py_version` to `TensorFlow`. See here: https://sagemaker.readthedocs.io/en/stable/v2.html#changes-in-default-behavior

Thanks for the review @paul-cb, I've run the notebook through the [upgrade CLI tool](https://sagemaker.readthedocs.io/en/stable/v2.html#automatically-upgrade-your-code). That seems to fix (2).

As for (1), I checked the source code and I still see the entire [`HyperparameterTuner`](https://github.com/aws/sagemaker-python-sdk/blob/c389c72314708fa3b9e4e6ff65443ca47fbeb644/src/sagemaker/tuner.py#L191) class. However, the documentation you linked does say "The delete_endpoint() method for estimators and HyperparameterTuner is now a no-op." Maybe it's only related to the `delete_endpoint()` method, which isn't used in this example notebook? Or is there another class or estimator that I should be using instead of `HyperparameterTuner`?

**Comment by ajaykarpur** [comment]
@paul-cb @wiltonwu Only the `delete_endpoint()` method is a no-op.

**Comment by paul-cb** [comment]
Thanks for your update @wiltonwu. Your changes look good but the notebook doesn't run. I ran it and it breaks on the `import utils` line. This is also causing the Build to break too. 

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-3bec7422fb64> in <module>
----> 1 import utils
      2 from tensorflow.contrib.learn.python.learn.datasets import mnist
      3 import tensorflow as tf
      4 
      5 data_sets = mnist.read_data_sets('data', dtype=tf.uint8, reshape=False, validation_size=5000)

ModuleNotFoundError: No module named 'utils'

**Comment by wiltonwu** [comment]
> Thanks for your update @wiltonwu. Your changes look good but the notebook doesn't run. I ran it and it breaks on the `import utils` line. This is also causing the Build to break too.
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-3-3bec7422fb64> in <module>
> ----> 1 import utils
>       2 from tensorflow.contrib.learn.python.learn.datasets import mnist
>       3 import tensorflow as tf
>       4 
>       5 data_sets = mnist.read_data_sets('data', dtype=tf.uint8, reshape=False, validation_size=5000)
> 
> ModuleNotFoundError: No module named 'utils'
> ```

I believe the `utils` module refers to the [`utils.py` file](https://github.com/aws/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/tensorflow_mnist/utils.py). I was able to successfully execute the notebook. @ajaykarpur does the automated codebuild job copy the entire directory (including the utils.py file) when executing via papermill? I suspect that may be why the build is failing

**Review by paul-cb — APPROVED** [review]
Approved.

**Pull request merged**
