### PR TITLE
Add pytorch mnist example with Elastic Inference

### PR DESCRIPTION
**Pull request by tracycxw**
*Issue #, if available:*

*Description of changes:*
Add pytorch mnist example notebook with Elastic Inference and add deploy_ei.py script

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by paul-cb** [comment]
Thanks @tracycxw! The notebook breaks for me because `torchvision` isn't imported. Could you fix this? 
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-3916aaf64ab2> in <module>
----> 1 from torchvision import datasets, transforms
      2 
      3 datasets.MNIST('data', download=True, transform=transforms.Compose([
      4     transforms.ToTensor(),
      5     transforms.Normalize((0.1307,), (0.3081,))

ModuleNotFoundError: No module named 'torchvision'
```

**Comment by tracycxw** [comment]
> Thanks @tracycxw! The notebook breaks for me because `torchvision` isn't imported. Could you fix this?
> 
> ```
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-2-3916aaf64ab2> in <module>
> ----> 1 from torchvision import datasets, transforms
>       2 
>       3 datasets.MNIST('data', download=True, transform=transforms.Compose([
>       4     transforms.ToTensor(),
>       5     transforms.Normalize((0.1307,), (0.3081,))
> 
> ModuleNotFoundError: No module named 'torchvision'
> ```

Hi @paul-cb , this example works on my notebook instance, and the code you point out is the same in existing [example](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/pytorch_mnist/pytorch_mnist.ipynb). I guess the reason the CI build failed is - it didn't use `conda_pytorch_p27` env. Is there a way to run this example with pytorch env in CI build?

**Comment by paul-cb** [comment]
Hi @tracycxw, what kernel version are you using? The notebook should be compatible with when using the `Python 3 (Data Science)` kernel in Studio.

**Comment by tracycxw** [comment]
i use kernel conda_pytorch_p27. Are u suggesting I should replace with
conda_pytorch_p36?

**Comment by paul-cb** [comment]
You can select any kernel available from the Studio UI. The notebook must be compatible with Studio, and not just in a native Jupyter notebook instance. Thanks!

**Comment by tracycxw** [comment]
please hold this PR for now.. need to modify some lines

**Review by paul-cb — APPROVED** [review]
Approved

**Pull request merged**
