### PR TITLE
Updated sagemaker attribute configurations for V2 SDK support

### PR DESCRIPTION
**Pull request by sdoyle88**
*Issue #, if available:*
No issues currently exist or previously closed

*Description of changes:*
Updated the Sagemaker introduction to sagemaker pca-mnist notebook code for support with the sagemaker v2 SDK.  Specific entries updated:
1.  Removed the ```content_type``` parameter, this no longer exists in **class sagemaker.predictor.Predictor** for v2
2.  Renamed the parameter for ```endpoint``` to ```endpoint_name``` as defined in v2 **class sagemaker.predictor.Predictor**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aaronmarkham — APPROVED** [review]
Seems to work, but isn't totally v2... had these warnings:

The method get_image_uri has been renamed in sagemaker>=2.
--> sagemaker.image_uris.retrieve()

train_instance_count has been renamed in sagemaker>=2.
--> instance_count

train_instance_type has been renamed in sagemaker>=2.
--> instance_type

The csv_serializer has been renamed in sagemaker>=2.
--> sagemaker.serializers.CSVSerializer

The json_deserializer has been renamed in sagemaker>=2.
--> sagemaker.deserializers.JSONDeserializer

Approving since it runs end-to-end... will wait to see if you want to address the rest before merging.

**Comment by aaronmarkham** [comment]
CI error:

{"outputs":[{"ename":"ModelError","output_type":"error","evalue":"An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message \"unable to evaluate payload provided\". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/pca-2020-10-29-17-45-32-744 in account 521695447989 for more information.

**Comment by sdoyle88** [comment]
> Seems to work, but isn't totally v2... had these warnings:
> 
> The method get_image_uri has been renamed in sagemaker>=2.
> --> sagemaker.image_uris.retrieve()
> 
> train_instance_count has been renamed in sagemaker>=2.
> --> instance_count
> 
> train_instance_type has been renamed in sagemaker>=2.
> --> instance_type
> 
> The csv_serializer has been renamed in sagemaker>=2.
> --> sagemaker.serializers.CSVSerializer
> 
> The json_deserializer has been renamed in sagemaker>=2.
> --> sagemaker.deserializers.JSONDeserializer
> 
> Approving since it runs end-to-end... will wait to see if you want to address the rest before merging.

I will see if I can update all of the code to V2, and submit another PR.

**Comment by sdoyle88** [comment]
> CI error:
> 
> {"outputs":[{"ename":"ModelError","output_type":"error","evalue":"An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "unable to evaluate payload provided". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/pca-2020-10-29-17-45-32-744 in account 521695447989 for more information.

Interesting, it ran when I tested it end to end in my notebook.  Is there a way to evaluate what the logs stated in CloudWatch in that account?  I see that error and a second error in the subsequent CI run that it hit an account limit error that blocked deploying the notebook.  

Could it be the CI Tester is running the tests with the wrong Sagemaker SDK version?   I noticed this output in the CI run as well, near the bottom of the notebook:

_"{"outputs":[{"ename":"AttributeError","output_type":"error","evalue":"'RealTimePredictor' object has no attribute 'endpoint_name'""_.  This is when the automation is trying to delete the endpoint during the first run.  If using the latest v2 Sagemaker SDK, this should exist in the RealTimePredictor class (v2 documentation: [https://sagemaker.readthedocs.io/en/stable/api/inference/predictors.html](url).  It could possibly explain why the first run failed to invoke the endpoint as well?

I will try to migrate all of the updates to v2, but curious if the reason for this CI build fail is due to the wrong SageMaker SDK being used for the test notebook instance.  I suppose we could hard code the requirement to download the updated version of the SDK in one of the first cells of the notebook as well.

**Pull request merged**
