### PR TITLE
Enable S3 Endpoint URL configuration

### PR DESCRIPTION
**Pull request by larsll**
This patch allows the DeepRacer example to be used in a fully local mode with a different S3 endpoint. This is part of the activities we do in the AWS Deepracer Community (https://github.com/aws-deepracer-community)

Code should be non-intrusive, and should in theory trickle into all places where the DeepRacer Markov-code is used, e.g. the Robomaker code.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aaronmarkham — CHANGES_REQUESTED** [review]
Hi, can you resolve the conflicts? I'll work with you to get it merged after that. Thanks!

**Comment by larsll** [comment]
@aaronmarkham  - if I understand correctly you have now done a full refresh of the markov package to reflect the latest simapp bundle, right? We have kept our patches up-to-date so I can re-do the PR with the latest.

Will you be able to feed the changes back into the 'upstream' for the changes to be permanent?

**Comment by larsll** [comment]
@aaronmarkham - this has now been updated with the latest markov code's need for adaptation.

**Comment by paul-cb** [comment]
This works and is ready to be merged.

**Comment by paul-cb** [comment]
All relevant `.py` files for Deepracer has support for different S3 endpoints. `s3_endpoint_url` has been added in all of the correct places. 

Approved.

**Review by paul-cb — COMMENTED** [review]
All relevant .py files for Deepracer has support for different S3 endpoints. s3_endpoint_url has been added in all of the correct places.

Approved.

**Review by paul-cb — APPROVED** [review]

**Pull request merged**
