### PR TITLE
min_df was larger than max_df and outside of the acceptable range of 0.0-1.0

### PR DESCRIPTION
**Pull request by aserfass**
min_df was larger than max_df and outside of the acceptable range of 0.0-1.0. This gave me an error but changing the min_df to 0.2 or 0.02 resolved the error. It is unclear if the author intended min_df to be 0.2 or 0.02.

*Issue #, if available:*

*Description of changes:*
I changed min_df to be within the acceptable range of values but the author should change this to the intended value (0.2 or 0.02).  Sorry for the formatting changes but I'm trying to make this feedback quick and Jupyter made the formatting changes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by IvyBazan** [comment]
@aserfass Can you give provide more information on the error code you're running into, as well as some information on your instance and kernel version?

**Comment by aserfass** [comment]
Hi Ivy,

The error code was “ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.” On a Jupyter notebook running Python 3.7.4

I looked up the inputs for min and max df and found this:
“min_dffloat in range [0.0, 1.0] or int, default=1…”

It says min_df can be an Int but max is a float and min is an Int, so the min is larger than the max

Let me know if you have any other questions

**Review by aaronmarkham — CHANGES_REQUESTED** [review]
Please clear the outputs to the notebook, then resubmit.

**Comment by aserfass** [comment]
@aaronmarkham hope the latest commit helps

**Review by aaronmarkham — APPROVED** [review]

**Comment by hsl89** [comment]
`min_df` tells the `CountVectorizer` to ignore words before certain frequency. So its valid range is between [0, 1]. The change makes sense.

**Review by hsl89 — APPROVED** [review]
LGTM

**Pull request merged**
